# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bb.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_ESP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ESP.setGeometry(QtCore.QRect(270, 11, 439, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_ESP.setFont(font)
        self.lineEdit_ESP.setEnabled(False)
        self.lineEdit_ESP.setObjectName("lineEdit_ESP")

        self.lineEdit_ESP3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ESP3.setGeometry(QtCore.QRect(595, 200, 85, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_ESP3.setFont(font)
        #self.lineEdit_ESP3.setEnabled(False)
        self.lineEdit_ESP3.setObjectName("lineEdit_ESP")

        self.label_ESP = QtWidgets.QLabel(self.centralwidget)
        self.label_ESP.setGeometry(QtCore.QRect(275, 195, 300, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(60)
        self.label_ESP.setFont(font)
        self.label_ESP.setObjectName("label_ESP")


        self.btnSTART = QtWidgets.QPushButton(self.centralwidget)
        self.btnSTART.setGeometry(QtCore.QRect(330, 290, 311, 111))
        self.btnSTART.setSizeIncrement(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(60)
        self.btnSTART.setFont(font)
        self.btnSTART.setIconSize(QtCore.QSize(30, 30))
        self.btnSTART.setCheckable(False)
        self.btnSTART.setObjectName("btnSTART")
        #self.btnSTART_2 = QtWidgets.QPushButton(self.centralwidget)
        #self.btnSTART_2.setGeometry(QtCore.QRect(620, 0, 311, 71))
       # self.btnSTART_2.setSizeIncrement(QtCore.QSize(10, 10))
        #font = QtGui.QFont()
       # font.setPointSize(16)
       # font.setBold(False)
        #font.setWeight(50)
       # self.btnSTART_2.setFont(font)
       # self.btnSTART_2.setIconSize(QtCore.QSize(30, 30))
        #self.btnSTART_2.setCheckable(False)
       # self.btnSTART_2.setObjectName("btnSTART_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 934, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setCheckable(False)
        self.openFile.setEnabled(True)
        self.openFile.setMenuRole(QtWidgets.QAction.NoRole)
        self.openFile.setObjectName("openFile")
        self.actionOpen_firmware = QtWidgets.QAction(MainWindow)
        self.actionOpen_firmware.setObjectName("actionOpen_firmware")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CHECKLIST"))
        self.lineEdit_ESP.setText(_translate("MainWindow", "     IMPRIMIR CHECKLIST"))
        self.btnSTART.setText(_translate("MainWindow", "IMPRIMIR"))

        self.label_ESP.setText(_translate("MainWindow", "QUANTIDADE DE PARES:"))

        #self.btnSTART_2.setText(_translate("MainWindow", "Acessar banco de dados"))
        self.openFile.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_firmware.setText(_translate("MainWindow", "Open firmware"))

